### ISSUE TITLE
Illegal moves

### ISSUE THREAD

**Issue by Matthies** [MetalPhaeton/sayuri#3]
Running your engine (ver. 2017.04.09) in a test tournament against other engines it sometimes makes illegal moves. It tries to castle although the rook is already captured.

Example1:
[Event "?"]
[Site "?"]
[Date "2017.09.22"]
[Round "28"]
[White "Cinnamon"]
[Black "Sayuri"]
[Result "1-0"]
[FEN "r1bqkbnr/ppppppp1/2n4p/1B6/4P3/8/PPPP1PPP/RNBQK1NR w KQkq - 0 1"]
[PlyCount "13"]
[SetUp "1"]
[Termination "illegal move"]
[TimeControl "40/10"]

1. Nf3 {+1.18/8 0.27s} f5 {-1.96/7 0.23s} 2. exf5 {+1.78/8 0.17s} d5 {-2.91/7 0.23s} 3. Ne5 {+3.13/10 0.25s} Nf6 {-2.92/7 0.23s} 4. Nxc6 {+2.78/9 0.23s} bxc6 {-3.25/9 0.23s} 5. Bxc6+ {+2.89/10 0.23s} Bd7 {-3.42/6 0.22s} 6. Bxa8 {+2.94/10 0.16s} Qxa8 {-3.12/7 0.22s} 7. Qf3 {+2.92/9 0.22s, Black makes an illegal move: e8c8} 1-0

Example 2:
[Event "?"]
[Site "?"]
[Date "2017.09.22"]
[Round "64"]
[White "Sayuri"]
[Black "Cinnamon"]
[Result "0-1"]
[FEN "rnbqkbnr/2pppppp/1p6/p7/2P5/5P2/PP1PP1PP/RNBQKBNR w KQkq - 0 1"]
[PlyCount "36"]
[SetUp "1"]
[Termination "illegal move"]
[TimeControl "40/10"]

1. d4 {+0.11/7 0.25s} e6 {+0.23/8 0.27s} 2. Nc3 {+0.01/7 0.23s} Nf6 {+0.21/7 0.25s} 3. e4 {+0.54/7 0.23s} Bb4 {+0.38/7 0.25s} 4. e5 {+0.12/7 0.23s} Nh5 {+0.25/8 0.23s} 5. d5 {-1.33/5 0.22s} Qh4+ {+2.85/8 0.23s} 6. g3 {-2.45/6 0.22s} Nxg3 {+3.22/9 0.23s} 7. hxg3 {-2.45/7 0.22s} Qxh1 {+3.31/9 0.22s} 8. Be3 {-2.96/6 0.19s} Qh2 {+3.15/6 0.22s} 9. Ne2 {-1.98/6 0.20s} Bxc3+ {+2.95/7 0.20s} 10. bxc3 {-2.18/6 0.20s} Bb7 {+3.02/7 0.20s} 11. f4 {-2.34/5 0.19s} Qh1 {+3.11/6 0.20s} 12. d6 {-1.89/6 0.19s} Qe4 {+3.23/8 0.19s} 13. Qd4 {-2.53/7 0.17s} c5 {+3.45/9 0.19s} 14. Qxe4 {-2.49/10 0.17s} Bxe4 {+3.26/10 0.19s} 15. Nc1 {-2.63/9 0.17s} Nc6 {+3.39/9 0.19s} 16. Bd3 {-2.68/9 0.17s} Bg6 {+3.25/8 0.13s} 17. Rb1 {-2.45/8 0.17s}
Rb8 {+3.28/9 0.17s} 18. Bxg6 {-2.35/9 0.16s} hxg6 {+3.72/8 0.17s, White makes an illegal move: e1g1} 0-1

**Comment by MetalPhaeton** [comment]
Thank you.
I have fixed it. (version 2017.09.26)
