### ISSUE TITLE
sayuri crushes on (rasp) jessie

### ISSUE THREAD

**Issue by LocutusOfPenguin** [MetalPhaeton/sayuri#5]
Hi,

using RaspberryPi Jessie (newest updates):

./sayuri 
uci
id name Sayuri 2017.09.29
id author Hironori Ishibashi
option name Hash type spin default 1 min 1 max 2048
option name Clear Hash type button
option name Ponder type check default true
option name Threads type spin default 1 min 1 max 64
option name UCI_AnalyseMode type check default false
uciok
go movetime 10
*** Error in `./sayuri': malloc(): memory corruption: 0x76dc257e ***
Aborted

my friend tried it out on sketch.
There it seems to work.

But our user base is still using jessie :-)

Jürgen

**Comment by LocutusOfPenguin** [comment]
Hmmm, i think, i found a possible solution:
g++ -std=c++11 -fno-rtti -Ofast -march=native -pthread -o sayuri *.cpp

Rasp seems to dislike this "native" ... if i change this to:
g++ -std=c++11 -fno-rtti -Ofast -mfloat-abi=hard -mlittle-endian -munaligned-access -pthread -o sayuri *.cpp

It seems to work on a Rasp2 (jessie) , Rasp3 (Sketch).

**Comment by MetalPhaeton** [comment]
I checked on Sayuri with Valgrind, but I didn't found any memory errors.
I found a web page : https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139091
The page says that the following compiler options are work for Raspberry Pi 3.
    -mcpu=cortex-a53 -mfpu=neon-vfpv4
I think you should use the options instead of '-march=native'.

**Comment by LocutusOfPenguin** [comment]
hi,
yes..i found something similar to it, therefore my second post. Thanks!

In meantime, i tried to leave away the "native" completely
g++ -std=c++11 -fno-rtti -Ofast -pthread -o sayuri *.cpp

and this also works.
Perhaps you update yr docu abit - if y want! - but i think, this issue can be closed.
Thanks again
