### ISSUE TITLE
Sayuri latest version problems with time forfeit on ChessGUI UCI-2 protocol

### ISSUE THREAD

**Issue by yellow-panther** [MetalPhaeton/sayuri#6]
Hello Hironori,

[Round "3.5"]
[White "ToppleChess"]
[Black "Sayuri 2018.05.23"]
[Result "1-0"]
[TimeControl "40/120:40/120:40/120"]
[Time "07:23:13"]
[PlyCount "63"]
[Number "17"]
[Termination "time"]
[BlackType "program"]
[WhiteType "program"]
[Variant "normal"]

1. e4 e5 2. Nc3 Nf6 3. a3 Bc5 4. Nf3 Ng4 5. d4 exd4 6. Na4 d6 7. b4 Bb6 8. Nxb6 axb6
9. Qxd4 O-O 10. Bb5 c6 11. h3 cxb5 12. hxg4 Nc6 13. Qd3 Nxb4 14. Qc3 Nc6 15. Bb2 f6 16. Qb3+ Rf7
17. Nd2 Bxg4 18. f3 Bd7 19. Rxh7 Na5 20. Qd5 Kxh7 21. Qxf7 Qe8 22. Qd5 Qe6 23. Qd4 Rc8 24. O-O-O Nb3+ 25. Nxb3 Qxb3 26. Qf2 b4 27. Kb1 Qa4 28. Rd4 b5 29. c3 Qb3 30. axb4 Rxc3 31. Rxd6 Bc6 32. Rd4 1-0 

[Round "3.6"]
[White "Sayuri 2018.05.23"]
[Black "ToppleChess"]
[Result "0-1"]
[TimeControl "40/120:40/120:40/120"]
[Time "07:27:16"]
[PlyCount "64"]
[Number "18"]
[Termination "time"]
[WhiteType "program"]
[BlackType "program"]
[Variant "normal"]

1. e3 Nf6 2. Nf3 a6 3. Nc3 d5 4. d4 Nc6 5. Bd3 Bg4 6. O-O e5 7. dxe5 Nxe5 8. Be2 Bxf3
9. Bxf3 Bb4 10. Bd2 Nc4 11. Be1 Nxb2 12. Qd4 c5 13. Qe5+ Kf8 14. Nxd5 Nc4 15. Qf4 Nxd5 16. Qxc4 Nb6
17. Qe4 Bxe1 18. Rfxe1 Rb8 19. Qf4 Na8 20. a4 Nc7 21. Rad1 Qe7 22. a5 b6 23. Rb1 b5 24. c3 g5
25. Qf5 Kg7 26. e4 b4 27. cxb4 Rxb4 28. Rbd1 Ne6 29. Qe5+ Qf6 30. Qd6 Ra4 31. e5 Qd8 32. Qb6 Qxb6 0-1 

[Round "4.5"]
[White "ToppleChess"]
[Black "Sayuri 2018.05.23"]
[Result "1-0"]
[TimeControl "40/120:40/120:40/120"]
[Time "07:46:13"]
[PlyCount "65"]
[Number "23"]
[Termination "time"]
[BlackType "program"]
[WhiteType "program"]
[Variant "normal"]

1. e4 e5 2. Nc3 Nf6 3. a3 Bc5 4. Nf3 Ng4 5. d4 exd4 6. Na4 d6 7. b4 Bb6 8. Nxb6 axb6
9. Qxd4 O-O 10. Bb5 c6 11. h3 cxb5 12. hxg4 Nc6 13. Qd3 Nxb4 14. Qc3 Nc6 15. Bb2 f6 16. Qb3+ Rf7
17. Nd2 Bxg4 18. f3 Bd7 19. Rxh7 Na5 20. Qd5 Kxh7 21. Qxf7 Qe8 22. Qd5 Qe6 23. Qd4 Rc8 24. O-O-O Nb3+ 25. Nxb3 Qxb3 26. Qf2 b4 27. Kb1 Qa4 28. Rd4 b5 29. c3 Qb3 30. axb4 Rxc3 31. Rxd6 Bc6 32. Rd4 g5  33. Qd2 1-0 

[Round "4.6"]
[White "Sayuri 2018.05.23"]
[Black "ToppleChess"]
[Result "0-1"]
[TimeControl "40/120:40/120:40/120"]
[Time "07:50:22"]
[PlyCount "74"]
[Number "24"]
[Termination "time"]
[WhiteType "program"]
[BlackType "program"]
[Variant "normal"]

1. e3 Nf6 2. Nf3 a6 3. Nc3 d5 4. d4 Nc6 5. Bd3 Bg4 6. O-O e5 7. dxe5 Nxe5 8. Be2 Bxf3
9. Bxf3 Bb4 10. Bxd5 Bxc3 11. Bxb7 Rb8 12. Qxd8+ Kxd8 13. Bxa6 Rb6 14. bxc3 Rxa6 15. Rd1+ Kc8 16. f4 Nc4  17. Rd4 Ra4 18. a3 c5 19. Rd3 Kc7 20. h4 Rb8 21. Kf2 Nb2 22. Bxb2 Rxb2 23. Kf3 Rxc2 24. g4 Ne4
25. c4 Nd2+ 26. Kg3 Raxc4 27. g5 R4c3 28. Rxc3 Rxc3 29. a4 Rxe3+ 30. Kg4 Ne4 31. f5 Nd6 32. Rf1 Ra3
33. Rf4 c4 34. h5 c3 35. g6 c2 36. gxh7 c1=Q 37. h8=Q Qg1+ 0-1 

[Round "5.6"]
[White "Sayuri 2018.05.23"]
[Black "ToppleChess"]
[Result "0-1"]
[TimeControl "40/120:40/120:40/120"]
[Time "08:14:03"]
[PlyCount "72"]
[Number "30"]
[Termination "time"]
[WhiteType "program"]
[BlackType "program"]
[Variant "normal"]

 1. e3 Nf6 2. Nf3 a6 3. Bd3 d5 4. O-O Nc6 5. c4 e6 6. cxd5 Nb4 7. Be2 exd5 8. a3 Nc6
 9. Nc3 Bg4 10. Qa4 h5 11. Ne5 Bxe2 12. Nxe2 Qd6 13. Nxc6 Qxc6 14. Qxc6+ bxc6 15. b3 Rb8 16. b4 Rh6
 17. d4 Rg6 18. Nf4 Rg4 19. f3 Rg5 20. Re1 Bd6 21. e4 dxe4 22. fxe4 Ng8 23. Nd3 Rg4 24. Bb2 h4
 25. e5 Bf8 26. Rac1 Ne7 27. h3 Rg3 28. Nc5 Nd5 29. Nxa6 Rb6 30. Nc5 Nf4 31. Rc2 Nxh3+ 32. Kh1 Nf4
 33. Rf1 Nd5 34. Rd2 Ne3 35. Rc1 Bxc5 36. dxc5 Rb8 0-1 

[Round "6.6"]
[White "Sayuri 2018.05.23"]
[Black "ToppleChess"]
[Result "0-1"]
[TimeControl "40/120:40/120:40/120"]
[Time "08:35:53"]
[PlyCount "70"]
[Number "36"]
[Termination "time"]
[WhiteType "program"]
[BlackType "program"]
[Variant "normal"]

1. Nc3 e5 2. Nf3 Nc6 3. e4 a6 4. Bc4 Bc5 5. O-O b5 6. Bd5 Nge7 7. d3 b4 8. Na4 Ba7
9. Bg5 f6 10. Be3 Nxd5 11. exd5 Ne7 12. c4 bxc3 13. Nxc3 Bb7 14. Qb3 Bxe3 15. fxe3 Rb8 16. Qc4 Nf5
17. Qg4 g6 18. Rae1 Bc8 19. b3 d6 20. Qa4+ Qd7 21. e4 Ne7 22. d4 Qxa4 23. Nxa4 Bd7 24. Nc3 O-O
25. Rd1 h6 26. Rd3 Kg7 27. Rf2 Rb4 28. Re2 a5 29. h3 h5 30. Kh1 Rfb8 31. dxe5 fxe5 32. Ng5 Rf8
33. Kg1 Rd4 34. Rf3 Rxf3 35. gxf3 c6 0-1 

All games and debug files included
[Topple.Chess.JB.zip](https://github.com/MetalPhaeton/sayuri/files/2083869/Topple.Chess.JB.zip)

ChessGUI website http://www.chess.hylogic.de/ 

Regards,

**Comment by MetalPhaeton** [comment]
I have received similar bug report from Norbert before.

I ran Sayuri in same situation with same UCI commands on my PC.
But Sayuri finished thinking in time correctly.

I tested several times, but I couldn't confirm such error.
So I can't fixed it.
